"""
Main entry point for Instagram AI Automation
Run this script to start the automation system
"""
import sys
import os
from typing import Optional
from instagram_ai import (
    get_logger,
    get_secrets,
    ContentGenerator,
    ImageHandler,
    InstagramAPI,
    CommentHandler,
    TaskScheduler
)

class InstagramAutomation:
    """Main automation orchestrator"""
    
    def __init__(self):
        """Initialize automation system"""
        self.logger = get_logger("instagram_automation")
        self.secrets = get_secrets()
        self.content_generator = ContentGenerator()
        self.image_handler = ImageHandler()
        self.instagram_api = InstagramAPI()
        self.comment_handler = CommentHandler()
        self.scheduler = TaskScheduler()
        
        self.logger.info("Instagram Automation System initialized")
    
    def validate_setup(self) -> bool:
        """
        Validate that all required credentials and setup are correct
        
        Returns:
            True if setup is valid
        """
        try:
            self.logger.info("Validating setup...")
            
            # Validate all secrets are set
            self.secrets.validate_all_secrets()
            self.logger.info("✓ All required environment variables are set")
            
            # Validate API access
            if not self.instagram_api.validate_access():
                self.logger.error("✗ Instagram API access validation failed")
                return False
            self.logger.info("✓ Instagram API access validated")
            
            self.logger.info("✓ Setup validation successful!")
            return True
            
        except Exception as e:
            self.logger.error(f"Setup validation failed: {str(e)}")
            return False
    
    def post_with_ai_content(
        self,
        image_path: str,
        content_niche: Optional[str] = None
    ) -> Optional[str]:
        """
        Generate AI content and post to Instagram
        
        Args:
            image_path: Path to image to post
            content_niche: Content niche (uses default if None)
        
        Returns:
            Post ID if successful, None otherwise
        """
        try:
            self.logger.info(f"Creating AI-generated post with image: {image_path}")
            
            # Validate and optimize image
            if not self.image_handler.validate_image(image_path):
                self.logger.error("Image validation failed")
                return None
            
            optimized_image = self.image_handler.optimize_image(image_path)
            self.logger.info(f"Image optimized: {optimized_image}")
            
            # Generate content
            content_data = self.content_generator.generate_caption(
                niche=content_niche
            )
            self.logger.info("Caption generated by AI")
            
            # Format caption
            formatted_caption = self.content_generator.format_caption_for_posting(content_data)
            
            # Create post (note: actual posting may require additional steps)
            self.logger.info("Posting to Instagram...")
            
            # This would be the actual posting call
            # post_id = self.instagram_api.create_post(optimized_image, formatted_caption)
            # For now, we'll just return the data
            
            self.logger.info("Post created successfully!")
            return formatted_caption
            
        except Exception as e:
            self.logger.error(f"Failed to create post: {str(e)}")
            return None
    
    def auto_reply_to_comments(self, post_id: str) -> dict:
        """
        Auto-reply to comments on a post using AI
        
        Args:
            post_id: Instagram post ID
        
        Returns:
            Summary of replies
        """
        try:
            self.logger.info(f"Processing comments for post: {post_id}")
            
            results = self.comment_handler.process_post_comments(post_id)
            
            self.logger.info(f"Comment processing results: {results}")
            return results
            
        except Exception as e:
            self.logger.error(f"Failed to process comments: {str(e)}")
            return {
                'total_comments': 0,
                'safe_comments': 0,
                'successful_replies': 0,
                'failed_replies': 0
            }
    
    def schedule_daily_posting(
        self,
        image_path: str,
        schedule_time: str = "09:00",
        content_niche: Optional[str] = None
    ):
        """
        Schedule daily AI-generated posts
        
        Args:
            image_path: Path to image to post
            schedule_time: Time in HH:MM format
            content_niche: Content niche
        """
        try:
            def post_task():
                self.post_with_ai_content(image_path, content_niche)
            
            self.scheduler.schedule_daily_post(
                post_task,
                time_str=schedule_time,
                task_name=f"daily_post_{schedule_time}"
            )
            
            self.logger.info(f"Scheduled daily post at {schedule_time}")
            
        except Exception as e:
            self.logger.error(f"Failed to schedule post: {str(e)}")
    
    def schedule_comment_checking(self, post_id: str, interval_minutes: int = 60):
        """
        Schedule automatic comment checking and replies
        
        Args:
            post_id: Instagram post ID to monitor
            interval_minutes: Check interval in minutes
        """
        try:
            def comment_task():
                self.auto_reply_to_comments(post_id)
            
            self.scheduler.schedule_every_interval(
                comment_task,
                interval=interval_minutes,
                unit="minutes",
                task_name=f"check_comments_{post_id}"
            )
            
            self.logger.info(f"Scheduled comment checking every {interval_minutes} minutes")
            
        except Exception as e:
            self.logger.error(f"Failed to schedule comment checking: {str(e)}")
    
    def start_scheduler(self):
        """Start the continuous scheduler"""
        try:
            self.logger.info("Starting continuous scheduler...")
            self.scheduler.print_schedule()
            self.scheduler.start_continuous(check_interval=60)
        except KeyboardInterrupt:
            self.logger.info("Scheduler stopped")
        except Exception as e:
            self.logger.error(f"Scheduler error: {str(e)}")
    
    def run_once(self):
        """Run all scheduled tasks once"""
        try:
            self.logger.info("Running all scheduled tasks once...")
            self.scheduler.run_all()
            self.logger.info("All tasks completed")
        except Exception as e:
            self.logger.error(f"Error running tasks: {str(e)}")


def main():
    """Main entry point"""
    try:
        # Initialize automation
        automation = InstagramAutomation()
        
        # Validate setup
        if not automation.validate_setup():
            sys.exit(1)
        
        # Example usage - uncomment to use:
        
        # Example 1: Post single image with AI-generated caption
        # automation.post_with_ai_content("path/to/image.jpg", content_niche="technology")
        
        # Example 2: Auto-reply to comments
        # automation.auto_reply_to_comments("instagram_post_id")
        
        # Example 3: Schedule daily posting
        # automation.schedule_daily_posting("path/to/image.jpg", schedule_time="09:00")
        
        # Example 4: Schedule comment checking
        # automation.schedule_comment_checking("instagram_post_id", interval_minutes=60)
        
        # Example 5: Start continuous scheduler
        # automation.start_scheduler()
        
        # Example 6: Run scheduled tasks once
        # automation.run_once()
        
        automation.logger.info("Instagram Automation System ready!")
        automation.logger.info("Configure and call desired methods to start automation")
        
    except Exception as e:
        print(f"Fatal error: {str(e)}")
        sys.exit(1)


if __name__ == "__main__":
    main()
